version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - '5432:5432'
    networks:
      project_network:


  project:
    container_name: project
    build:
      context: ./
    ports:
      - '3000:3000'
    command: npm run start:dev
    depends_on:
      - db
    networks:
      project_network:

networks:
  project_network: